import { supabase } from './seed_client';

async function seedModelsOnly() {
  console.log('Seeding Models Only...');

  const models = [
    { id: "mobilenet-v2", name: "MobileNet V2", description: "MobileNetV2 architecture optimized for mobile vision applications.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/MobileNet-v2/resolve/main/mobilenet_v2.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/mobilenet-v2/metadata.json", file_size_bytes: 14079072, version: "1.0", format: "tflite" },
    { id: "mobilenet-v3-small", name: "MobileNet V3 Small", description: "MobileNetV3 Small architecture optimized for mobile vision applications.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/MobileNet-v3-small/resolve/main/mobilenet_v3_small.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/mobilenet-v3-small/metadata.json", file_size_bytes: 10184432, version: "1.0", format: "tflite" },
    { id: "mobilenet-v3-large", name: "MobileNet V3 Large", description: "MobileNetV3 Large architecture optimized for mobile vision applications.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/MobileNet-v3-large/resolve/main/mobilenet_v3_large.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/mobilenet-v3-large/metadata.json", file_size_bytes: 21924224, version: "1.0", format: "tflite" },
    { id: "resnet18", name: "ResNet 18", description: "ResNet 18 architecture optimized for computer vision.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/resnet18/resolve/main/resnet18.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/resnet18/metadata.json", file_size_bytes: 46750944, version: "1.0", format: "tflite" },
    { id: "resnet50", name: "ResNet 50", description: "ResNet 50 architecture optimized for computer vision.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/resnet50/resolve/main/resnet50.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/resnet50/metadata.json", file_size_bytes: 102148096, version: "1.0", format: "tflite" },
    { id: "efficientnet-b0", name: "EfficientNet B0", description: "EfficientNet B0 architecture optimized for computer vision.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/efficientnet_b0/resolve/main/efficientnet_b0.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/efficientnet-b0/metadata.json", file_size_bytes: 21319488, version: "1.0", format: "tflite" },
    { id: "vit-tiny", name: "ViT Tiny", description: "Vision Transformer (Tiny) architecture.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/vit_tiny_patch16_224/resolve/main/model.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/vit-tiny/metadata.json", file_size_bytes: 22978000, version: "1.0", format: "tflite" },
    { id: "vit-base-augreg", name: "ViT Base", description: "Vision Transformer (Base) architecture.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/vit_base_patch16_224.augreg_in1k/resolve/main/vit_base_patch16_224_fp32.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/vit-base-augreg/metadata.json", file_size_bytes: 346216112, version: "1.0", format: "tflite" },
    { id: "yolov8n-detect", name: "YOLOv8 Nano (Detect)", description: "Real-time object detection model optimized for edge devices.", task_type: "object-detection", file_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolov8n-detect/model.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolov8n-detect/metadata.json", file_size_bytes: 12841243, version: "1.0", format: "litert" },
    { id: "yolov8n-cls", name: "YOLOv8 Nano (Classify)", description: "Image classification model for edge devices.", task_type: "image-classification", file_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolov8n-cls/model.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolov8n-cls/metadata.json", file_size_bytes: 10917171, version: "1.0", format: "litert" },
    { id: "yolov8n-pose", name: "YOLOv8 Nano (Pose)", description: "Real-time human pose estimation model.", task_type: "pose-estimation", file_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolov8n-pose/model.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolov8n-pose/metadata.json", file_size_bytes: 13510234, version: "1.0", format: "litert" },
    { id: "yolov8n-seg", name: "YOLOv8 Nano (Seg)", description: "Real-time instance segmentation model.", task_type: "instance-segmentation", file_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolov8n-seg/model.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolov8n-seg/metadata.json", file_size_bytes: 13876205, version: "1.0", format: "litert" },
    { id: "yolox-nano-litert", name: "YOLOX Nano", description: "A lightweight and high-performance anchor-free object detector, optimized for real-time edge devices.", task_type: "object-detection", file_url: "https://huggingface.co/litert-community/yolox-nano-litert/resolve/main/yolox_nano.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/yolox-nano-litert/metadata.json", file_size_bytes: 2236912, version: "1.0", format: "tflite" },
    { id: "mediapipe-selfie-segmentation", name: "Selfie Segmentation (Multiclass)", description: "MediaPipe Selfie Segmentation model. Segments the person into multi-class parts.", task_type: "image-segmentation", file_url: "https://huggingface.co/litert-community/MediaPipe-Selfie-Segmentation/resolve/main/selfie_multiclass.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/mediapipe-selfie-segmentation/metadata.json", file_size_bytes: 16371837, version: "1.0", format: "tflite" },
    { id: "deeplabv3-resnet50", name: "DeepLabV3 ResNet-50", description: "DeepLabV3 model with a ResNet-50 backbone for semantic segmentation (21 classes).", task_type: "image-segmentation", file_url: "https://huggingface.co/litert-community/deeplabv3_resnet50/resolve/main/deeplabv3_resnet50.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/deeplabv3-resnet50/metadata.json", file_size_bytes: 158472352, version: "1.0", format: "tflite" },
    { id: "ormbg-litert", name: "ormbg (Open Remove-Background)", description: "High-quality photorealistic subject cut-out (Background Removal).", task_type: "image-segmentation", file_url: "https://huggingface.co/litert-community/ormbg-LiteRT/resolve/main/ormbg.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/ormbg-litert/metadata.json", file_size_bytes: 176240148, version: "1.0", format: "tflite" },
    { id: "rtmpose-s", name: "RTMPose Small", description: "State-of-the-art 2D human pose estimation (17 keypoints).", task_type: "pose-estimation", file_url: "https://huggingface.co/litert-community/RTMPose-s-LiteRT/resolve/main/rtmpose_s_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/rtmpose-s/metadata.json", file_size_bytes: 11139472, version: "1.0", format: "tflite" },
    { id: "rtmw-wholebody", name: "RTMW WholeBody", description: "Whole-body 2D pose (133 keypoints: body, face, hands, feet).", task_type: "pose-estimation", file_url: "https://huggingface.co/litert-community/RTMW-m-WholeBody-LiteRT/resolve/main/rtmw_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/rtmw-wholebody/metadata.json", file_size_bytes: 66137312, version: "1.0", format: "tflite" },
    { id: "rtmpose-face", name: "RTMPose Face (WFLW)", description: "Facial landmarks detection (98 keypoints).", task_type: "pose-estimation", file_url: "https://huggingface.co/litert-community/RTMPose-Face-WFLW-LiteRT/resolve/main/rtm_face_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/rtmpose-face/metadata.json", file_size_bytes: 33622896, version: "1.0", format: "tflite" },
    { id: "rtmpose-hand", name: "RTMPose Hand", description: "Hand keypoints detection (21 keypoints).", task_type: "pose-estimation", file_url: "https://huggingface.co/litert-community/RTMPose-Hand-LiteRT/resolve/main/rtmhand_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/rtmpose-hand/metadata.json", file_size_bytes: 27827248, version: "1.0", format: "tflite" },
    { id: "rtmpose-animal", name: "RTMPose Animal", description: "Animal keypoints detection (17 keypoints).", task_type: "pose-estimation", file_url: "https://huggingface.co/litert-community/RTMPose-Animal-AP10K-LiteRT/resolve/main/rtm_animal_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/rtmpose-animal/metadata.json", file_size_bytes: 27526176, version: "1.0", format: "tflite" },
    { id: "real-esrgan-x4v3", name: "Real-ESRGAN x4 (Super Resolution)", description: "Upscales and enhances image resolution by 4x using Real-ESRGAN.", task_type: "image-to-image", file_url: "https://huggingface.co/litert-community/real-esrgan-x4v3-litert/resolve/main/realesr_general_x4v3.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/real-esrgan-x4v3/metadata.json", file_size_bytes: 3549456, version: "1.0", format: "tflite" },
    { id: "fast-neural-style-candy", name: "Neural Style - Candy", description: "Applies the Candy artistic style to the image.", task_type: "image-to-image", file_url: "https://huggingface.co/litert-community/Fast-Neural-Style-LiteRT/resolve/main/style_candy_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/fast-neural-style-candy/metadata.json", file_size_bytes: 3482944, version: "1.0", format: "tflite" },
    { id: "fast-neural-style-mosaic", name: "Neural Style - Mosaic", description: "Applies the Mosaic artistic style to the image.", task_type: "image-to-image", file_url: "https://huggingface.co/litert-community/Fast-Neural-Style-LiteRT/resolve/main/style_mosaic_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/fast-neural-style-mosaic/metadata.json", file_size_bytes: 3482944, version: "1.0", format: "tflite" },
    { id: "fast-neural-style-rain-princess", name: "Neural Style - Rain Princess", description: "Applies the Rain Princess artistic style to the image.", task_type: "image-to-image", file_url: "https://huggingface.co/litert-community/Fast-Neural-Style-LiteRT/resolve/main/style_rain_princess_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/fast-neural-style-rain-princess/metadata.json", file_size_bytes: 3482944, version: "1.0", format: "tflite" },
    { id: "fast-neural-style-udnie", name: "Neural Style - Udnie", description: "Applies the Udnie artistic style to the image.", task_type: "image-to-image", file_url: "https://huggingface.co/litert-community/Fast-Neural-Style-LiteRT/resolve/main/style_udnie_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/fast-neural-style-udnie/metadata.json", file_size_bytes: 3482944, version: "1.0", format: "tflite" },
    { id: "depth-anything-3-small", name: "Depth Anything 3 Small", description: "Monocular depth estimation (single RGB image to depth map).", task_type: "depth-estimation", file_url: "https://huggingface.co/litert-community/Depth-Anything-3-Small/resolve/main/da3_small_gpu_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/depth-anything-3-small/metadata.json", file_size_bytes: 55035456, version: "1.0", format: "tflite" },
    { id: "hsemotion-b0", name: "HSEmotion B0", description: "EfficientNet-B0 based facial emotion recognition model trained on AffectNet dataset. Classifies 8 basic emotions.", task_type: "image-classification", file_url: "https://huggingface.co/litert-community/HSEmotion-B0-LiteRT/resolve/main/hsemotion_b0_fp16.tflite", metadata_url: "https://cdn.jsdelivr.net/gh/iAmHieu2012/sequoia-models@main/hsemotion-b0/metadata.json", file_size_bytes: 8291808, version: "1.0", format: "tflite" }
  ];
  
  const { error: mErr } = await supabase.from('models').upsert(models);
  if (mErr) throw mErr;

  console.log('✅ Models seeded successfully!');
  process.exit(0);
}

seedModelsOnly();
