ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.hcmus.sequoia.FirebaseConfigKt.configureFirebase
      com.hcmus.sequoia.HttpKt.configureHttp
      com.hcmus.sequoia.SerializationKt.configureSerialization
      com.hcmus.sequoia.SecurityKt.configureSecurity
      com.hcmus.sequoia.RoutingKt.configureRouting
    ]
  }
}