ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.hcmus.HttpKt.configureHttp
      com.hcmus.SerializationKt.configureSerialization
      com.hcmus.SecurityKt.configureSecurity
      com.hcmus.RoutingKt.configureRouting
    ]
  }
}