ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.hcmus.sequoia.plugins.FirebaseConfigKt.configureFirebase
      com.hcmus.sequoia.plugins.HttpKt.configureHttp
      com.hcmus.sequoia.plugins.SerializationKt.configureSerialization
      com.hcmus.sequoia.plugins.SecurityKt.configureSecurity
      com.hcmus.sequoia.plugins.ErrorHandlingKt.configureErrorHandling
      com.hcmus.sequoia.plugins.RateLimitingKt.configureRateLimiting
      com.hcmus.sequoia.routes.RoutingKt.configureRouting
    ]
  }
}